#------------------------------------------------------------------------------#
# FleCSI Gitlab CI: Main
#------------------------------------------------------------------------------#

stages:
  - Checks
  - MPI backend
  - HPX backend
  - Legion backend
  - Standalone

variables:
  ENABLED_CLUSTERS: darwin

include:
 - .gitlab/common.yml
 - .gitlab/checks.yml
 - .gitlab/mpi.yml
 - .gitlab/hpx.yml
 - .gitlab/legion.yml
 - .gitlab/standalone.yml
