var searchData=
[
  ['set',['set',['../structflecsi_1_1topo_1_1set.html',1,'flecsi::topo']]],
  ['set_5fspecialization',['set_specialization',['../structflecsi_1_1topo_1_1set__specialization.html',1,'flecsi::topo']]],
  ['sort_5fentity',['sort_entity',['../classflecsi_1_1topo_1_1sort__entity.html',1,'flecsi::topo']]],
  ['span',['span',['../structflecsi_1_1util_1_1span.html',1,'flecsi::util']]],
  ['span_3c_20element_5ftype_20_3e',['span&lt; element_type &gt;',['../structflecsi_1_1util_1_1span.html',1,'flecsi::util']]],
  ['span_3c_20pair_5ft_20_3e',['span&lt; pair_t &gt;',['../structflecsi_1_1util_1_1span.html',1,'flecsi::util']]],
  ['specialization',['specialization',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20array_5fcategory_2c_20array_3c_20p_20_3e_20_3e',['specialization&lt; array_category, array&lt; P &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20borrow_5fcategory_2c_20borrow_3c_20flecsi_3a_3atopo_3a_3aresize_20_3e_20_3e',['specialization&lt; borrow_category, borrow&lt; flecsi::topo::resize &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20borrow_5fcategory_2c_20borrow_3c_20q_20_3e_20_3e',['specialization&lt; borrow_category, borrow&lt; Q &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20borrow_5fcategory_2c_20borrow_3c_20topo_3a_3ameta_3c_20q_20_3e_20_3e_20_3e',['specialization&lt; borrow_category, borrow&lt; topo::meta&lt; Q &gt; &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20column_2c_20claims_20_3e',['specialization&lt; column, claims &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20column_2c_20resize_20_3e',['specialization&lt; column, resize &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20detail_3a_3abuffers_5fcategory_2c_20buffers_20_3e',['specialization&lt; detail::buffers_category, buffers &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20global_5fcategory_2c_20global_20_3e',['specialization&lt; global_category, global &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20index_5fcategory_2c_20index_20_3e',['specialization&lt; index_category, index &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20narray_2c_20narray_5fspecialization_20_3e',['specialization&lt; narray, narray_specialization &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20ragged_5fcategory_2c_20ragged_3c_20t_20_3e_20_3e',['specialization&lt; ragged_category, ragged&lt; T &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20ragged_5fpartition_5fcategory_2c_20ragged_5fpartition_3c_20n_20_3e_20_3e',['specialization&lt; ragged_partition_category, ragged_partition&lt; N &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20set_2c_20set_5fspecialization_20_3e',['specialization&lt; set, set_specialization &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20topo_3a_3aarray_5fcategory_2c_20intervals_20_3e',['specialization&lt; topo::array_category, intervals &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20topo_3a_3acolor_2c_20halves_20_3e',['specialization&lt; topo::color, halves &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20unstructured_2c_20example_20_3e',['specialization&lt; unstructured, example &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20user_2c_20ctopo_20_3e',['specialization&lt; user, ctopo &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20user_2c_20meta_3c_20p_20_3e_20_3e',['specialization&lt; user, meta&lt; P &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_3c_20user_2c_20meta_3c_20policy_20_3e_20_3e',['specialization&lt; user, meta&lt; Policy &gt; &gt;',['../structflecsi_1_1topo_1_1specialization.html',1,'flecsi::topo']]],
  ['specialization_5fbase',['specialization_base',['../structflecsi_1_1topo_1_1specialization__base.html',1,'flecsi::topo']]],
  ['state',['state',['../classflecsi_1_1flog_1_1state.html',1,'flecsi::flog']]],
  ['sub_5frange',['sub_range',['../structflecsi_1_1exec_1_1sub__range.html',1,'flecsi::exec']]],
  ['substring_5fview',['substring_view',['../structflecsi_1_1util_1_1substring__view.html',1,'flecsi::util']]],
  ['sum',['sum',['../structflecsi_1_1exec_1_1fold_1_1sum.html',1,'flecsi::exec::fold']]],
  ['symbol',['Symbol',['../structflecsi_1_1util_1_1Symbol.html',1,'flecsi::util']]]
];
