macro(flecsi_enable_mpi ENABLE_CXX_BINDINGS)
  find_package(Threads REQUIRED)
  list(APPEND TPL_LIBRARIES Threads::Threads)
  if(ENABLE_CXX_BINDINGS)
    find_package(MPI COMPONENTS C MPICXX REQUIRED)
    list(APPEND TPL_LIBRARIES MPI::MPI_CXX)
    set(MPI_LANGUAGE CXX)
  else()
    find_package(MPI COMPONENTS C REQUIRED)
    list(APPEND TPL_LIBRARIES MPI::MPI_C)
    set(MPI_LANGUAGE C)
  endif()
endmacro()
