option(ENABLE_PARMETIS "Enable ParMETIS" OFF)

if(ENABLE_PARMETIS)
  find_package(METIS REQUIRED)

  set(PARMETIS_TEST_RUNS TRUE)
  find_package(ParMETIS REQUIRED)

  list(APPEND TPL_INCLUDES ${PARMETIS_INCLUDE_DIRS} ${METIS_INCLUDE_DIRS})
  list(APPEND TPL_LIBRARIES ${METIS_LIBRARIES} ${PARMETIS_LIBRARIES})
endif()
